### ISSUE TITLE
Qwen-VL and mPLUG-Owl2 yaml

### ISSUE THREAD

**Issue by kailinjiang** [VLKEB/VLKEB#2]
Why do yaml files for Qwen-VL and mPLUG-Owl2 not exist in hparams?

**Comment by JZSAWYER** [comment]
Thank you for bringing this to our attention. The YAML files for Qwen-VL and mPLUG-Owl2 are currently not available in the hparams directory due to some pending updates. We are actively working on updating the codes for these two models and will ensure that the necessary YAML files are included soon. Please stay tuned for the upcoming updates.

**Comment by kailinjiang** [comment]
Thank you for your reply! Looking forward to your update!

**Comment by JZSAWYER** [comment]
> Thank you for your reply! Looking forward to your update!

Hi @kailinjiang,
We have now uploaded all the necessary codes and the corresponding YAML files for the Qwen-VL and mPLUG-Owl2 models. You can find them in the repo. Thank you for your patience!

**Comment by kailinjiang** [comment]
Thank you very much for your work！！！
